In [1]:
import numpy as np

A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

In [2]:
dimensions = {
    'A': np.shape(A),
    'B': np.shape(B),
    'C': np.shape(C),
    'D': np.shape(D),
    'u': np.shape(u),
    'v': np.shape(v)
}

In [3]:
dimensions

{'A': (2, 3), 'B': (2, 2), 'C': (3, 2), 'D': (2, 3), 'u': (4,), 'v': (4,)}

In [4]:
# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

alpha = 6

u_plus_v = u+v             # u+v
u_minus_v = u-v           # u-v
alpha_times_u = alpha*u        # alpha * u, alpha = 6
u_dot_v = np.dot(u,v)             # u . v
from numpy import linalg as LA
norm_u = LA.norm(u)              # ||u|| 

In [5]:
u_plus_v, u_minus_v, alpha_times_u, u_dot_v, norm_u

(array([ 9,  7, -4,  9]),
 array([ 3, -3, -2,  1]),
 array([ 36,  12, -18,  30]),
 51,
 8.602325267042627)

In [6]:

# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C = None            # A + C
A_minus_Ctranspose = A-np.transpose(C)    # A - C.T
Ctranspose_plus_3D = np.transpose(C)+3*D   # C.T + 3*D
B_times_A = np.matmul(B,A)            # B*A
B_times_Atranspose = None   # B*A.T

In [7]:
A_minus_Ctranspose,Ctranspose_plus_3D, B_times_A

(array([[-4, -7, -3],
        [ 3,  6,  4]]), array([[14,  3,  3],
        [ 2,  7,  9]]), array([[-1, -5, -1],
        [ 2,  7,  4]]))

In [8]:
# Q4: (bonus)

B_times_C = None          # B*C
C_times_B = np.matmul(C,B)            # C*B
B_exp_4 = B^4              # B^4
A_times_Atranspose = np.matmul(A,np.transpose(A))  # A*A.T
Dtranspose_times_D = np.matmul(np.transpose(D),D)   # D.T*D

In [9]:
B_times_C,C_times_B,B_exp_4,A_times_Atranspose,Dtranspose_times_D

(None, array([[ 5, -6],
        [ 9, -8],
        [ 6, -6]]), array([[ 5, -5],
        [ 4,  5]]), array([[14, 28],
        [28, 69]]), array([[10, -4,  0],
        [-4,  8,  8],
        [ 0,  8, 10]]))